#//trust-fabric/ops/compose/docker-compose.yml
networks:
  tf_net: {}

volumes:
  pg_org1: {}
  pg_reg: {}
  ipfs_data: {}
  besu_data: {}
  acapy_issuer_wallet: {}
  acapy_verifier_wallet: {}
  firefly_org1_data: {}
  firefly_reg_data: {}

services:
  besu:
    image: "${BESU_IMAGE}:${BESU_TAG}"
    container_name: besu
    user: "0:0"
    command: >
      --network=dev
      --data-path=/data
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,WEB3,TXPOOL,ADMIN,CLIQUE
      --rpc-ws-enabled
      --rpc-ws-api=ETH,NET,WEB3,TXPOOL,CLIQUE
      --host-allowlist=*
      --min-gas-price=0
      --data-storage-format=BONSAI
    ports:
      - "${BESU_HTTP:-8545}:8545"
      - "${BESU_WS:-8546}:8546"
    networks: [tf_net]
    volumes:
      - besu_data:/data

  ipfs:
    image: ipfs/kubo:v0.28.0
    container_name: ipfs
    environment:
      IPFS_PROFILE: server
    ports:
      - "${IPFS_API:-5001}:5001"
    networks: [tf_net]
    volumes:
      - ipfs_data:/data/ipfs

  postgres_org1:
    image: "${POSTGRES_IMAGE}:${POSTGRES_TAG}"
    container_name: pg_org1
    environment:
      POSTGRES_PASSWORD: firefly
      POSTGRES_USER: firefly
      POSTGRES_DB: firefly
    networks: [tf_net]
    volumes:
      - pg_org1:/var/lib/postgresql/data

  evmconnect_org1:
    image: "${FF_EVMCONNECT_IMAGE}:${FF_EVMCONNECT_TAG}"
    container_name: evmconnect_org1
    environment:
      EVMCONNECT_CONFIG_PATH: /etc/evmconnect/firefly.evmconnect.yaml
      EVMCONNECT_NODE_URL: http://besu:8545
      EVMCONNECT_CONFIRMATIONS_REQUIRED: 0
      EVMCONNECT_POLLINGINTERVAL: 1s
      EVMCONNECT_TXCACHESIZE: 1000
      EVMCONNECT_HTTP_PORT: 3000
    command: ["-f", "/etc/evmconnect/firefly.evmconnect.yaml"]  # ADD THIS
    networks: [tf_net]
    volumes:
      - ./config/evmconnect/org1:/etc/evmconnect:ro  # FIXED PATH
    depends_on:
      - besu

  dx_org1:
    image: "${FF_DX_IMAGE}:${FF_DX_TAG}"
    container_name: dx_org1
    environment:
      DX_HTTPS_BIND_ADDRESS: 0.0.0.0
      DX_HTTPS_PUBLIC_URL: http://dx_org1:3001
    ports:
      - "3001:3001"
    networks: [tf_net]
    volumes:
      - ./config/dx:/data:ro  # FIXED PATH

  firefly_org1:
    image: "${FF_CORE_IMAGE}:${FF_CORE_TAG}"
    container_name: firefly_org1
    # REMOVED redundant environment variables (using config file instead)
    ports:
      - "${FF_ORG1:-5000}:5000"
    networks: [tf_net]
    volumes:
      - firefly_org1_data:/firefly
      - ./config/firefly/org1:/etc/firefly:ro  # FIXED PATH
    depends_on:
      - postgres_org1
      - evmconnect_org1
      - ipfs
      - dx_org1

  firefly_console:
    build:
      context: ../../ui-src
      dockerfile: Dockerfile
      args:
        REACT_APP_FF_ENDPOINT: http://localhost:${FF_ORG1:-5000}
    image: local/firefly-ui:dev
    pull_policy: never
    container_name: firefly_console
    environment:
      REACT_APP_FF_ENDPOINT: http://localhost:${FF_ORG1:-5000}
    ports:
      - "${FF_UI:-3000}:3000"
    networks: [tf_net]
    depends_on:
      - firefly_org1

  postgres_reg:
    image: "${POSTGRES_IMAGE}:${POSTGRES_TAG}"
    container_name: pg_reg
    environment:
      POSTGRES_PASSWORD: firefly
      POSTGRES_USER: firefly
      POSTGRES_DB: firefly
    networks: [tf_net]
    volumes:
      - pg_reg:/var/lib/postgresql/data

  evmconnect_reg:
    image: "${FF_EVMCONNECT_IMAGE}:${FF_EVMCONNECT_TAG}"
    container_name: evmconnect_reg
    command: ["-f", "/etc/evmconnect/firefly.evmconnect.yaml"]  # ADD THIS
    environment:
      EVMCONNECT_CONFIG_PATH: /etc/evmconnect/firefly.evmconnect.yaml
      EVMCONNECT_NODE_URL: http://besu:8545
      EVMCONNECT_CONFIRMATIONS_REQUIRED: 0
      EVMCONNECT_POLLINGINTERVAL: 1s
      EVMCONNECT_TXCACHESIZE: 1000
      EVMCONNECT_HTTP_PORT: 3000
    networks: [tf_net]
    volumes:
      - ./config/evmconnect/reg:/etc/evmconnect:ro  # FIXED PATH
    depends_on:
      - besu

  firefly_reg:
    image: "${FF_CORE_IMAGE}:${FF_CORE_TAG}"
    container_name: firefly_reg
    # REMOVED redundant environment variables (using config file instead)
    ports:
      - "${FF_REG:-5100}:5000"
    networks: [tf_net]
    volumes:
      - firefly_reg_data:/firefly
      - ./config/firefly/reg:/etc/firefly:ro  # FIXED PATH
    depends_on:
      - postgres_reg
      - evmconnect_reg
      - ipfs

  acapy_issuer:
    image: "${ACAPY_IMAGE}:${ACAPY_TAG}"
    container_name: acapy_issuer
    command: >
      start
      --inbound-transport http 0.0.0.0 8030
      --outbound-transport http
      --admin 0.0.0.0 8031
      --label IssuerAgent
      --endpoint http://acapy_issuer:8030
      --wallet-type askar-anoncreds --wallet-name issuer --wallet-key insecure
      --auto-provision
      --auto-accept-invites
      --auto-accept-requests
      --admin-insecure-mode
      --no-ledger
    ports:
      - "8030:8030"
      - "8031:8031"
    networks: [tf_net]
    volumes:
      - acapy_issuer_wallet:/home/aries/.askar/

  acapy_verifier:
    image: "${ACAPY_IMAGE}:${ACAPY_TAG}"
    container_name: acapy_verifier
    command: >
      start
      --inbound-transport http 0.0.0.0 8040
      --outbound-transport http
      --admin 0.0.0.0 8041
      --label VerifierAgent
      --endpoint http://acapy_verifier:8040
      --wallet-type askar-anoncreds --wallet-name verifier --wallet-key insecure
      --auto-provision
      --auto-accept-invites
      --auto-accept-requests
      --admin-insecure-mode
      --no-ledger  # FIXED: removed extra dash
    ports:
      - "8040:8040"
      - "8041:8041"
    networks: [tf_net]
    volumes:
      - acapy_verifier_wallet:/home/aries/.askar/